### ISSUE TITLE
Criar website para visualizar dados

### ISSUE THREAD

**Issue by sibelius** [nazareno/houseofcunha#5]
Seria útil um website para visualizar esses dados.

Eu recomento usar o [React](https://github.com/facebook/react) para as Views e [D3](https://github.com/mbostock/d3) para visualização de dados.

**Comment by ricardoas** [comment]
O site está disponível em: http://houseofcunha.com.br
(código do branch gh-pages)

**Comment by sibelius** [comment]
obrigado

**Comment by ricardoas** [comment]
:smiley_cat:
