### ISSUE TITLE
Identificação dos eixos de análise

### ISSUE THREAD

**Issue by meneguzzi** [nazareno/houseofcunha#6]
Quando vi a página com a análise das posições, fiquei confuso sobre o que cada eixo representa. Isto são as mesmas dimensões daquele [political compass](http://politicalcompass.org) (minha primeira intuição), isto é, esquerda e direita, autoritarismo e libertarismo, ou isto são dimensões diferentes? 

Seria legal só colocar um texto nos gráficos indicando o que as dimensões representam.

**Comment by RodolfoViana** [comment]
As dimensões são definidas com base nas votações de todas as proposições votadas até agora em 2015. Atualmente estamos trabalhando na melhor forma de informar o que cada dimensão representa (que segue um pouco a sua intuição).

Muito obrigado pela sugestão, contribuições são bem-vindas.

**Comment by meneguzzi** [comment]
Então tu estás usando como dimensões cada uma das proposições e usa algum algoritmo de aprendizado não supervisionado para reduzir a dimensionalidade para dois? O que eu sugeriria era classificar cada resposta de questão como esquerda/direita e libertário/autoritário e usar isto para criar a visualização. A classificação é gerada no código em R ou na parte python?

**Comment by RodolfoViana** [comment]
Na verdade não, 
A gente usa uma técnica de redução de dimensão utilizando um método estatístico chamado Multiple Correspondence Analysis, uma técnica de redução de dimensionalidade para dados categóricos (essa última frase só deve fazer sentido se você gostar muito de estatística e Mineração de Dados). Quando um deputado não vota sim ou não, assumimos que ele concorda com a maioria.

Você pode encontrar todo o código no nosso github.
