### ISSUE TITLE
Duplicidade de deputado

### ISSUE THREAD

**Issue by augusto-herrmann** [nazareno/houseofcunha#8]
A imagem em http://houseofcunha.com.br/images/partidos-gg.png apresenta o nome do Dep. Miro Teixeira (PROS/RJ) duas vezes, em locais diferentes: próximo ao pequeno aglomerado não identificado no centro da imagem e também um pouco acima, a meio caminho do cluster do PSOL.

**Comment by RodolfoViana** [comment]
Obrigado pela observação. 
Esse erro ocorreu pois o deputado trocou de partido. Nessa nova versão, quando um deputado troca de partido todo o seu histórico de votação é mantido.
